### ISSUE TITLE
Nightlog data are being modified after sync is complete

### ISSUE THREAD

**Issue by weaverba137** [desihub/desinightlog#8]
In the process of trying to recover nightlog sync data after the restoration of line internet to KPNO, I discovered that files at KPNO were being modified after the sync of those files to NERSC was complete. The timestamps indicate that sometimes this happened days after the conclusion of the night.

The nightlog sync only targets nightlog data from the current night, so if a file is modified after the end of that night, that change will not get synced.

Why are files being modified in this way, and is it expected that late-modified files will never get  updated at NERSC?

**Comment by jalasker** [comment]
This is not an issue. 

NERSC log is synced as a measure of convenience prior to all observers having VPN Access. KPNO log is log of record. I have considered removing NERSC log support entirely, especially considering that we have survived the last couple months without syncing those logs. 

If the question is whether or not the nightlogs should be allowed to be modified after an OBSDATE, then that can be discussed but this is not an issue as posed.
